USE customer_analysis;

SELECT * FROM cleaned_data LIMIT 20;

# what is the total revenue generated by male vs female customers ?

SELECT gender , SUM(purchase_amount) as revenue
from cleaned_data
group by gender;


#which customers used a discount but still spent more than average purchase amount?

SELECT customer_id, purchase_amount
FROM cleaned_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from cleaned_data);

#which are the top 5 products with the highest review rate

SELECT item_purchased , ROUND(AVG(review_rating),2) as 'Average product rating'
from cleaned_data
group by item_purchased
order by avg(review_rating) DESC
LIMIT 5;

#Compare the average purchase amounts between standard and express shipping

select shipping_type,
avg(purchase_amount)
from cleaned_data
where shipping_type in ('Standard','Express')
group by shipping_type;


#do subscribed customers spend more? compare avg spend and total revenue between subsribers and non-subscribers

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from cleaned_data
group by subscription_status
order by total_revenue , avg_spend desc;


#which 5 products have highest percentage of purchase with discounts applied

SELECT item_purchased,
       ROUND(
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
           / COUNT(*),
           2
       ) AS discount_rate
FROM cleaned_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# Segement customers into new , returning , and loyal based on their total number of previoud purchases , and show the count of each segment

with customer_type as (
select customer_id , previous_purchases,
case 
 when previous_purchases = 1 then 'New'
 when previous_purchases between 2 and 10 then 'Returning'
 else 'Loyal'
 end as customer_segment
from cleaned_data
)

select customer_segment , count(*) as number_of_customers
from customer_type
group by customer_segment;

#what are the top 3 most purchased products within each category

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM cleaned_data
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


#are customers who are repeat buyers (more tha 5 previous purchases) also likely to subscribe

select subscription_status,
count(customer_id) as repeat_buyers
from cleaned_data
where previous_purchases > 5
group by subscription_status;


# what is the revenue contribution of each age group

select age_group,
sum(purchase_amount) as total_revenue
from cleaned_data
group by age_group
order by total_revenue desc;